# ==============================================================================
# MIL-STD-498 MESSAGE BROKER CONFIGURATION FILE
# ==============================================================================
# SYSTEM:             Rootcastle Home Watcher Stack
# SUBSYSTEM:          MQTT Broker Subsystem (Mosquitto)
# FILE NAME:          mosquitto.conf
# VERSION:            1.2.0
# DATE:               2026-06-15
# SECURITY CLASSIF:   UNCLASSIFIED
# DESCRIPTION:        Configures the MQTT listener bindings and broker persistence.
# ==============================================================================
listener 1883 0.0.0.0
allow_anonymous true

persistence true
persistence_location /mosquitto/data/

log_dest stdout
